language: minimal

services:
- docker

matrix:
  include:
  - image: debian:9
  - image: ubuntu:18.04
  - image: ubuntu:16.04
  - image: ubuntu:14.04
  - image: kalilinux/kali-linux-docker

install:
- "./.travis/install.sh"

script:
- "./.travis/test.sh"
