language: minimal

services:
- docker

matrix:
  include:
  - env: IMAGE=debian:9
  - env: IMAGE=ubuntu:18.04
  - env: IMAGE=ubuntu:16.04
  - env: IMAGE=ubuntu:14.04
  - env: IMAGE=kalilinux/kali-linux-docker

install:
- "./.travis/install.sh"

script:
- "./.travis/test.sh"
